Documentation action similar to Purify
astro-informatics/sopt pull request #266
Opened 2022-01-04 17:15 UTC by SJaffa

From the Travis file the documentation build seems pretty similar to the Purify one.

2022-01-04 17:26 UTC, SJaffa commented
Installing dependencies is the slowest part of this (49s of the 1m13) so if we want to speed it up I should check all the dependencies are necessary. This is the list we used for Purify, sopt might not need all of them.

2022-01-14 15:36 UTC, tkoskela requested changes

2022-01-14 15:36 UTC, tkoskela commented on .github/workflows/documentation.yml
> +        run: sudo apt install libfftw3-dev libtiff5-dev libboost-all-dev libeigen3-dev libyaml-cpp-dev libcfitsio-dev casacore-dev doxygen graphviz
It runs successfully for me with this subset of dependencies
```suggestion
        run: sudo apt install libtiff5-dev openmpi-bin libopenmpi-dev libeigen3-dev libyaml-cpp-dev doxygen graphviz
```

2022-01-14 15:36 UTC, tkoskela commented on .github/workflows/documentation.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-01-21 11:05 UTC, tkoskela approved these changes

2022-01-21 11:06 UTC, merged