Tk/decomposition refactor forward backward
astro-informatics/sopt pull request #305
Opened 2022-10-12 13:35 UTC by tkoskela

Refactor the class `ImagingForwardBackward` so that the `g_proximal` function is provided by a separate class. The public interface to provide `g_proximal` is the abstract base class `GProximal`. An implementation of the interface for the L1 proximal is added in `L1GProximal`, which holds the code specific to the L1 proximal that was previously in `ImagingForwardBackward`.

Remaining open issues
- [ ] Add the `Psi` operator to the interface. It is an operator that transforms the image to a different base. In many cases it is not needed and a unit matrix can be used by default.
- [ ] Add a parameter to decide which implementation of `GProximal` to instantiate based on input.
- [ ] Do a similar refactor of `L2ForwardBackward`
- [ ] Modify l1 proximal as described in #298 
- [ ] Add more comments

2022-11-02 15:27 UTC, tkoskela commented
MacOS with apple-clang fails to find OpenMP on GitHub actions. Same problem appears in the development branch so something must have broken on the GA runners. Created issue #308

2022-11-03 16:39 UTC, SJaffa commented on cpp/sopt/l1_g_proximal.h
> +  //! Calls l1 proximal operator, checking for thight frame
```suggestion
  //! Calls l1 proximal operator, checking for tight frame
```

2022-11-03 16:40 UTC, SJaffa commented on cpp/sopt/l1_g_proximal.h
> +  //! Calls l1 proximal operator, checking for real constraints and tight frame
```suggestion
  //! Calls l1 proximal operator, checking for real constraints
```
I think this bit only checks for the real constraint, tight frame is checked in the `call_l1_proximal`

2022-11-03 16:41 UTC, SJaffa commented on cpp/sopt/l1_g_proximal.h
> +// E.g.: `paddm.l1_proximal_itermax(100).l1_proximal_tolerance(1e-4)`.
Great to add this explanation of the macro, makes it much clearer why we have this and how it is used.

2022-11-03 16:46 UTC, SJaffa requested changes
My only requests were a couple of typos in the comments, but the new structure looks great, so much easier to follow the logic and should make it much easier to adapt in the future.

2022-11-10 13:29 UTC, CosmoMatt commented
@tkoskela from what I can tell this looks great, and if @SJaffa has also taken a read through the PR we should be fine to merge into main. The only issue is this failing test, we really should try and avoid merging failing tests into main, is there any way around this?

2022-11-17 13:39 UTC, CosmoMatt approved these changes
This looks fine to me :)

2022-11-22 16:31 UTC, SJaffa approved these changes

2022-11-23 14:54 UTC, merged